[build]
rustc-wrapper = "sccache"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "target-cpu=native",
    "-Z",
    "share-generics=y",
    "-Z",
    "threads=0",
]

[profile.dev]
codegen-backend = "cranelift"
debug = false
opt-level = 1

[profile.dev.package."*"]
codegen-backend = "llvm"
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[unstable]
codegen-backend = true
