[build]
rustc-wrapper = "sccache"
rustflags = [
  "-Clink-arg=-fuse-ld=mold",
  "-Ctarget-cpu=native",
  "-Zshare-generics=yes",
  "-Zthreads=0",
]

[profile.dev]
codegen-backend = "cranelift"
debug = "line-tables-only"
opt-level = 1

[profile.dev.package."*"]
codegen-backend = "llvm"
debug = "none"
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"

[unstable]
codegen-backend = true
gc = true
