general {
    before_sleep_cmd = loginctl lock-session
    lock_cmd = swaylock
}

listener {
    on-resume = mmsg dispatch wakeup_monitor,eDP-1
    on-timeout = mmsg dispatch sleep_monitor,eDP-1
    timeout = 150
}

listener {
    on-timeout = swaylock
    timeout = 300
}

listener {
    on-timeout = systemctl suspend
    timeout = 600
}
